name: Opens a new PR if there are OpenAPI updates
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  auto-update:
    uses: tryAGI/workflows/.github/workflows/auto-update.yml@main
    with:
      library-path: src/libs/Ollama
    secrets: inherit
