name: Publish
on:
  push:
    branches:
      - main
    tags:
      - v**
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Publish
    uses: tryAGI/workflows/.github/workflows/generated-sdk-publish.yml@main
    with:
      project-path: src/libs/Ollama/Ollama.csproj
      dotnet-version: 10.0.x
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'
    secrets:
      nuget-key: ${{ secrets.NUGET_KEY }}
