name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    if: github.event.pull_request.draft == false
    uses: tryAGI/workflows/.github/workflows/generated-sdk-pull-request.yml@main
    with:
      project-path: src/libs/Ollama/Ollama.csproj
      dotnet-version: 10.0.x
      enable-caching: false
      additional-test-arguments: '--logger GitHubActions'
